name: ESLint

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci
      working-directory: utils/eslint/

    - name: Run ESLint
      run: npx eslint . --debug
      working-directory: utils/eslint/

    - name: Cache node modules and .eslintrc.js
      uses: actions/cache@v2
      with:
        path: |
          utils/eslint/node_modules
          utils/eslint/.eslintrc.js
        # Modify cache keys for restoration
        key: ${{ runner.os }}-eslintrc-${{ hashFiles('utils/eslint/.eslintrc.js') }}-node-modules-${{ hashFiles('utils/eslint/package-lock.json') }}
